# -*- mode: python ; coding: utf-8 -*-
from pathlib import Path

# SPECPATH do PyInstaller cung cấp và luôn trỏ tới thư mục chứa spec. Nhờ đó
# build-panel.ps1 có thể được gọi từ bất kỳ working directory nào mà pathex vẫn
# là project root, không vô tình import/package file ở thư mục đang đứng.
project = Path(SPECPATH).parent
datas = [
    ("ui", "wfx_panel/ui"),
    ("manual", "wfx_panel/manual"),
    ("assets/wfx.ico", "wfx_panel/assets"),
    ("../Article List.csv", "."),
]
sync_config = project / "wfx_panel" / "assets" / "sync-config.json"
if sync_config.is_file():
    datas.append((str(sync_config), "wfx_panel/assets"))
# Lưu ý: đường dẫn nguồn (script/datas trái/icon) trong spec được PyInstaller
# phân giải tương đối SPECPATH (thư mục chứa chính file .spec này), tức
# wfx_panel/ — không phải theo cwd lúc gọi lệnh build. Vì spec nằm ở
# wfx_panel/wfx-panel.spec nên các đường dẫn nguồn ở đây viết tương đối so
# với wfx_panel/ ("panel_app.py", "ui", "assets/wfx.ico"), còn vế đích của
# datas vẫn giữ "wfx_panel/..." để khớp wfx_panel/prefs.py APP_DIR (parent.parent
# của module đã đóng gói) khi ứng dụng chạy ở dạng frozen.
a = Analysis(
    ["panel_app.py"],
    pathex=[str(project)],
    binaries=[],
    datas=datas,
    hiddenimports=[
        "login",
        "wfx_panel.controllers",
        "wfx_panel.controllers.access",
        "wfx_panel.controllers.catalog",
        "wfx_panel.controllers.catalog_files",
        "wfx_panel.controllers.catalog_style",
        "wfx_panel.controllers.costing",
        "wfx_panel.controllers.directory",
        "wfx_panel.controllers.finance",
        "wfx_panel.controllers.inventory",
        "wfx_panel.controllers.jobs",
        "wfx_panel.controllers.modules",
        "wfx_panel.controllers.oc",
        "wfx_panel.controllers.reports",
        "wfx_panel.controllers.sale_asn",
        "wfx_panel.controllers.session",
        "wfx_panel.controllers.settings",
        "wfx_panel.manual_book",
        "wfx_panel._signing_identity",
        "wfx_panel.secret",
        "wfx_panel.app",
        "wfx_panel.app.bridges",
        "wfx_panel.app.tray",
        "wfx_panel.app.notifications",
        "wfx_panel.app.background",
        "wfx_panel.app.bubble",
        "wfx_panel.app.dialogs",
        "wfx_panel.app.helpers",
        "wfx_panel.app.layout",
        "wfx_panel.app.manual_window",
        "wfx_panel.app.placement",
        "wfx_panel.run_engine",
        "wfx_panel.stores.panel_cache",
        "wfx_panel.paths",
        "wfx_panel.run_policy",
        "wfx_panel.telemetry_labels",
        "wfx_panel.automation",
        "wfx_panel.automation.browser",
        "wfx_panel.automation.session",
        "wfx_panel.automation.bulk_style",
        "wfx_panel.automation.bulk_style.constants",
        "wfx_panel.automation.bulk_style.frames",
        "wfx_panel.automation.bulk_style.editor",
        "wfx_panel.automation.bulk_style.flows",
        "wfx_panel.automation.catalog",
        "wfx_panel.automation.costing",
        "wfx_panel.automation.modules",
        "wfx_panel.automation.oc",
        "wfx_panel.automation.oc.constants",
        "wfx_panel.automation.oc.dom",
        "wfx_panel.automation.oc.package",
        "wfx_panel.automation.oc.transaction",
        "wfx_panel.automation.oc.confirm",
        "wfx_panel.automation.oc.flows",
        "wfx_panel.automation.directory",
        "wfx_panel.automation.directory.frames",
        "wfx_panel.automation.directory.supplier_open",
        "wfx_panel.automation.directory.company_query",
        "wfx_panel.automation.directory.supplier_search",
        "wfx_panel.automation.directory.buyer",
        "wfx_panel.automation.dispatch",
        "wfx_panel.automation.dispatch.constants",
        "wfx_panel.automation.dispatch.status",
        "wfx_panel.automation.dispatch.report",
        "wfx_panel.automation.dispatch.edi",
        "wfx_panel.automation.dispatch.flows",
        "wfx_panel.automation.grn",
        "wfx_panel.automation.grn.constants",
        "wfx_panel.automation.grn.frames",
        "wfx_panel.automation.grn.controls",
        "wfx_panel.automation.grn.receipt",
        "wfx_panel.automation.grn.search",
        "wfx_panel.automation.sale_asn_create",
        "wfx_panel.automation.sale_asn_documents",
        "wfx_panel.automation.sale_asn_documents.constants",
        "wfx_panel.automation.sale_asn_documents.grid",
        "wfx_panel.automation.sale_asn_documents.report",
        "wfx_panel.automation.sale_asn_documents.flow",
        "wfx_panel.automation.reports",
        "wfx_panel.automation._common",
        "wfx_panel.workbooks",
        "wfx_panel.workbooks.asn",
        "wfx_panel.workbooks.asn.ooxml",
        "wfx_panel.workbooks.asn.cells",
        "wfx_panel.workbooks.asn.layout",
        "wfx_panel.workbooks.asn.packing",
        "wfx_panel.workbooks.asn.merge",
        "wfx_panel.workbooks.costing_planner",
        "wfx_panel.workbooks.costing",
        "wfx_panel.workbooks.costing.schema",
        "wfx_panel.workbooks.costing.writer",
        "wfx_panel.workbooks.costing.reader",
        "wfx_panel.workbooks.oc",
        "wfx_panel.workbooks.oc.schema",
        "wfx_panel.workbooks.oc.values",
        "wfx_panel.workbooks.oc.template",
        "wfx_panel.workbooks.oc.rows",
        "wfx_panel.workbooks.oc.upload",
        "wfx_panel.workbooks.sale_asn",
        "wfx_panel.workbooks.style",
        "wfx_panel.stores",
        "wfx_panel.stores.article_library",
        "wfx_panel.stores.reference_sync",
        "wfx_panel.stores.report_parameters",
        "wfx_panel.stores.sale_asn_buyers",
        "wfx_panel.stores.style_options",
        "openpyxl",
        "pystray._win32",
        "keyboard",
    ],
    hookspath=[],
    runtime_hooks=[],
    # WFX Smart chạy pywebview bằng WebView2/WinForms trên Windows. Các backend
    # Qt cùng dependency phân tích ảnh/ký SSL tùy chọn bị hook của pywebview và
    # Pillow kéo vào dù app không gọi tới; loại chúng giúp giảm hơn 100 MB mà
    # không đụng tới Playwright hoặc pythonnet cần cho runtime thật.
    excludes=[
        "PyQt5",
        "PyQt6",
        "PySide2",
        "PySide6",
        "numpy",
        "cryptography",
        "yaml",
        "psutil",
        "tkinter",
        "IPython",
        "matplotlib",
    ],
)
pyz = PYZ(a.pure)
exe = EXE(pyz, a.scripts, [], exclude_binaries=True, name="WFX-Panel",
          console=False, icon="assets/wfx.ico", version="version_info.txt")
coll = COLLECT(exe, a.binaries, a.datas, name="WFX-Panel")
